// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcOEokaeA3x7tqpTnb8-M_-Ko5gYO1YoI',
    appId: '1:382194592458:web:28e2bdd33f8b20599d2233',
    messagingSenderId: '382194592458',
    projectId: 'kratos-5ed40',
    authDomain: 'kratos-5ed40.firebaseapp.com',
    storageBucket: 'kratos-5ed40.firebasestorage.app',
    measurementId: 'G-P26D7P46KQ',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl4ox49uFvmV0KpvzrLwg_i0SfaAKNOo0',
    appId: '1:382194592458:android:00ff013be64edda99d2233',
    messagingSenderId: '382194592458',
    projectId: 'kratos-5ed40',
    storageBucket: 'kratos-5ed40.firebasestorage.app',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiRWQftBJ-stR4AaVvi2zbGCmIHBHwTCg',
    appId: '1:382194592458:ios:91f465c10e7c90e09d2233',
    messagingSenderId: '382194592458',
    projectId: 'kratos-5ed40',
    storageBucket: 'kratos-5ed40.firebasestorage.app',
    iosBundleId: 'com.example.kratos',
  );
}
