"""initial_ai_models

Revision ID: 65d9858b12c0
Revises: 
Create Date: 2026-05-21 12:22:24.985360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '65d9858b12c0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_conversations',
    sa.Column('firebase_uid', sa.String(length=128), nullable=False, comment='Firebase UID of the user'),
    sa.Column('conversation_id', sa.UUID(), nullable=False, comment='Groups messages into a conversation thread'),
    sa.Column('turn_index', sa.Integer(), nullable=False, comment='Message order within the conversation (0-based)'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='Message role: user | assistant | system | tool'),
    sa.Column('user_message', sa.Text(), nullable=True, comment="The user's input message"),
    sa.Column('ai_response', sa.Text(), nullable=True, comment="The AI's generated response"),
    sa.Column('agent_type', sa.String(length=50), nullable=False, comment='Which agent handled this: assistant | planner | recovery | nutrition | progression'),
    sa.Column('model_used', sa.String(length=100), nullable=False, comment='Gemini model used for this response'),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True, comment='Number of prompt (input) tokens'),
    sa.Column('completion_tokens', sa.Integer(), nullable=True, comment='Number of completion (output) tokens'),
    sa.Column('total_tokens', sa.Integer(), nullable=True, comment='Total tokens (prompt + completion)'),
    sa.Column('latency_ms', sa.Float(), nullable=True, comment='End-to-end response latency in milliseconds'),
    sa.Column('context_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional context sent to the model (user profile snapshot, etc.)'),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Tool/function calls made during this turn'),
    sa.Column('feedback_rating', sa.Integer(), nullable=True, comment='User satisfaction rating (1–5)'),
    sa.Column('was_regenerated', sa.Boolean(), server_default='false', nullable=False, comment='Whether the user requested a regeneration'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='UUID4 primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp (server-side)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp (auto-refreshed on UPDATE)'),
    sa.PrimaryKeyConstraint('id'),
    comment='AI conversation history with token/cost tracking'
    )
    op.create_index('ix_ai_conversations_agent_type', 'ai_conversations', ['agent_type'], unique=False)
    op.create_index('ix_ai_conversations_conversation_id', 'ai_conversations', ['conversation_id'], unique=False)
    op.create_index('ix_ai_conversations_created_at', 'ai_conversations', ['created_at'], unique=False)
    op.create_index('ix_ai_conversations_firebase_uid', 'ai_conversations', ['firebase_uid'], unique=False)
    op.create_index('ix_ai_conversations_uid_conv', 'ai_conversations', ['firebase_uid', 'conversation_id'], unique=False)
    op.create_table('ai_insights',
    sa.Column('firebase_uid', sa.String(length=128), nullable=False, comment='Firebase UID of the user this insight belongs to'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='Insight category: workout | nutrition | recovery | general | progression'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Short human-readable insight title'),
    sa.Column('content', sa.Text(), nullable=False, comment='Full insight text / analysis body'),
    sa.Column('priority', sa.String(length=20), server_default='medium', nullable=False, comment='Priority level: low | medium | high | critical'),
    sa.Column('model_used', sa.String(length=100), nullable=False, comment='Gemini model that generated this insight'),
    sa.Column('confidence_score', sa.Float(), nullable=True, comment='AI confidence in this insight (0.0 – 1.0)'),
    sa.Column('source_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Source context/data the AI used to generate this insight'),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="Searchable tags: ['plateau', 'bench_press', 'strength']"),
    sa.Column('is_dismissed', sa.Boolean(), server_default='false', nullable=False, comment='Whether the user dismissed this insight'),
    sa.Column('is_acted_upon', sa.Boolean(), server_default='false', nullable=False, comment='Whether the user took action on this insight'),
    sa.Column('feedback_rating', sa.Integer(), nullable=True, comment='User rating of insight quality (1–5)'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='When this insight becomes stale (nullable = never expires)'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='UUID4 primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp (server-side)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp (auto-refreshed on UPDATE)'),
    sa.PrimaryKeyConstraint('id'),
    comment='AI-generated fitness insights and analysis results'
    )
    op.create_index('ix_ai_insights_category', 'ai_insights', ['category'], unique=False)
    op.create_index('ix_ai_insights_created_at', 'ai_insights', ['created_at'], unique=False)
    op.create_index('ix_ai_insights_firebase_uid', 'ai_insights', ['firebase_uid'], unique=False)
    op.create_index('ix_ai_insights_priority', 'ai_insights', ['priority'], unique=False)
    op.create_index('ix_ai_insights_uid_category', 'ai_insights', ['firebase_uid', 'category'], unique=False)
    op.create_table('ai_request_logs',
    sa.Column('firebase_uid', sa.String(length=128), nullable=True, comment='Firebase UID (nullable for system calls)'),
    sa.Column('endpoint', sa.String(length=255), nullable=False, comment='API endpoint that triggered this call'),
    sa.Column('agent_type', sa.String(length=50), nullable=False, comment='Agent: assistant|planner|recovery|nutrition|progression'),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='success', nullable=False, comment='success|error|timeout|rate_limited'),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_type', sa.String(length=100), nullable=True),
    sa.Column('request_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Request headers, params, etc.'),
    sa.Column('response_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Response metadata, safety ratings, etc.'),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=True, comment='Estimated cost in USD'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='UUID4 primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp (server-side)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp (auto-refreshed on UPDATE)'),
    sa.PrimaryKeyConstraint('id'),
    comment='AI API call observability and cost tracking'
    )
    op.create_index('ix_ai_request_logs_created_at', 'ai_request_logs', ['created_at'], unique=False)
    op.create_index('ix_ai_request_logs_endpoint', 'ai_request_logs', ['endpoint'], unique=False)
    op.create_index('ix_ai_request_logs_firebase_uid', 'ai_request_logs', ['firebase_uid'], unique=False)
    op.create_index('ix_ai_request_logs_model_used', 'ai_request_logs', ['model_used'], unique=False)
    op.create_index('ix_ai_request_logs_status', 'ai_request_logs', ['status'], unique=False)
    op.create_table('recommendation_logs',
    sa.Column('firebase_uid', sa.String(length=128), nullable=False),
    sa.Column('domain', sa.String(length=50), nullable=False, comment='workout|nutrition|recovery|supplement|lifestyle'),
    sa.Column('recommendation_type', sa.String(length=50), nullable=False, comment='exercise_swap|volume_adjust|meal_plan|rest_day|deload'),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True, comment='AI chain-of-thought'),
    sa.Column('trigger_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_context_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('priority', sa.String(length=20), server_default='medium', nullable=False),
    sa.Column('was_seen', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('was_accepted', sa.Boolean(), nullable=True),
    sa.Column('user_feedback', sa.Text(), nullable=True),
    sa.Column('outcome_status', sa.String(length=30), nullable=True, comment='pending|positive|neutral|negative|unknown'),
    sa.Column('outcome_measured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='UUID4 primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp (server-side)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp (auto-refreshed on UPDATE)'),
    sa.PrimaryKeyConstraint('id'),
    comment='AI recommendation tracking with feedback loop'
    )
    op.create_index('ix_rec_logs_created_at', 'recommendation_logs', ['created_at'], unique=False)
    op.create_index('ix_rec_logs_domain', 'recommendation_logs', ['domain'], unique=False)
    op.create_index('ix_rec_logs_firebase_uid', 'recommendation_logs', ['firebase_uid'], unique=False)
    op.create_index('ix_rec_logs_outcome', 'recommendation_logs', ['outcome_status'], unique=False)
    op.create_index('ix_rec_logs_uid_domain', 'recommendation_logs', ['firebase_uid', 'domain'], unique=False)
    op.create_table('recovery_metrics',
    sa.Column('firebase_uid', sa.String(length=128), nullable=False, comment='Firebase UID of the user'),
    sa.Column('metric_date', sa.Date(), nullable=False, comment='Date this metric was computed for'),
    sa.Column('metric_type', sa.String(length=50), nullable=False, comment='Metric type: daily_score | weekly_trend | fatigue_map | overtraining_risk'),
    sa.Column('recovery_score', sa.Float(), nullable=False, comment='AI-computed recovery score (0.0 – 100.0)'),
    sa.Column('risk_level', sa.String(length=20), server_default='low', nullable=False, comment='Risk level: low | moderate | high | critical'),
    sa.Column('readiness_status', sa.String(length=20), server_default='ready', nullable=False, comment='Training readiness: ready | caution | rest'),
    sa.Column('sleep_quality_score', sa.Float(), nullable=True, comment='AI-assessed sleep quality (0.0 – 10.0)'),
    sa.Column('soreness_index', sa.Float(), nullable=True, comment='Aggregated soreness index from user reports'),
    sa.Column('training_load_7d', sa.Float(), nullable=True, comment='Rolling 7-day training load metric'),
    sa.Column('hrv_trend', sa.Float(), nullable=True, comment='HRV trend value if available'),
    sa.Column('analysis_summary', sa.Text(), nullable=True, comment='AI-generated human-readable recovery analysis'),
    sa.Column('muscle_fatigue_map', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="Per-muscle-group fatigue levels: {'chest': 0.7, 'legs': 0.3, ...}"),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="AI recovery recommendations: ['deload', 'sleep_more', ...]"),
    sa.Column('contributing_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="Factors that influenced the score: {'sleep': -0.2, 'volume': -0.1}"),
    sa.Column('model_used', sa.String(length=100), nullable=False, comment='AI model that computed this metric'),
    sa.Column('confidence', sa.Float(), nullable=True, comment='AI confidence in this metric (0.0 – 1.0)'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='UUID4 primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp (server-side)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp (auto-refreshed on UPDATE)'),
    sa.PrimaryKeyConstraint('id'),
    comment='AI-computed recovery analytics and trend data'
    )
    op.create_index('ix_recovery_metrics_firebase_uid', 'recovery_metrics', ['firebase_uid'], unique=False)
    op.create_index('ix_recovery_metrics_metric_date', 'recovery_metrics', ['metric_date'], unique=False)
    op.create_index('ix_recovery_metrics_metric_type', 'recovery_metrics', ['metric_type'], unique=False)
    op.create_index('ix_recovery_metrics_risk_level', 'recovery_metrics', ['risk_level'], unique=False)
    op.create_index('ix_recovery_metrics_uid_date', 'recovery_metrics', ['firebase_uid', 'metric_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recovery_metrics_uid_date', table_name='recovery_metrics')
    op.drop_index('ix_recovery_metrics_risk_level', table_name='recovery_metrics')
    op.drop_index('ix_recovery_metrics_metric_type', table_name='recovery_metrics')
    op.drop_index('ix_recovery_metrics_metric_date', table_name='recovery_metrics')
    op.drop_index('ix_recovery_metrics_firebase_uid', table_name='recovery_metrics')
    op.drop_table('recovery_metrics')
    op.drop_index('ix_rec_logs_uid_domain', table_name='recommendation_logs')
    op.drop_index('ix_rec_logs_outcome', table_name='recommendation_logs')
    op.drop_index('ix_rec_logs_firebase_uid', table_name='recommendation_logs')
    op.drop_index('ix_rec_logs_domain', table_name='recommendation_logs')
    op.drop_index('ix_rec_logs_created_at', table_name='recommendation_logs')
    op.drop_table('recommendation_logs')
    op.drop_index('ix_ai_request_logs_status', table_name='ai_request_logs')
    op.drop_index('ix_ai_request_logs_model_used', table_name='ai_request_logs')
    op.drop_index('ix_ai_request_logs_firebase_uid', table_name='ai_request_logs')
    op.drop_index('ix_ai_request_logs_endpoint', table_name='ai_request_logs')
    op.drop_index('ix_ai_request_logs_created_at', table_name='ai_request_logs')
    op.drop_table('ai_request_logs')
    op.drop_index('ix_ai_insights_uid_category', table_name='ai_insights')
    op.drop_index('ix_ai_insights_priority', table_name='ai_insights')
    op.drop_index('ix_ai_insights_firebase_uid', table_name='ai_insights')
    op.drop_index('ix_ai_insights_created_at', table_name='ai_insights')
    op.drop_index('ix_ai_insights_category', table_name='ai_insights')
    op.drop_table('ai_insights')
    op.drop_index('ix_ai_conversations_uid_conv', table_name='ai_conversations')
    op.drop_index('ix_ai_conversations_firebase_uid', table_name='ai_conversations')
    op.drop_index('ix_ai_conversations_created_at', table_name='ai_conversations')
    op.drop_index('ix_ai_conversations_conversation_id', table_name='ai_conversations')
    op.drop_index('ix_ai_conversations_agent_type', table_name='ai_conversations')
    op.drop_table('ai_conversations')
    # ### end Alembic commands ###
