"""Change meal id to string

Revision ID: 9cc4d0e786bf
Revises: d20bec2f3d2e
Create Date: 2026-08-13 23:42:13.258382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cc4d0e786bf'
down_revision: Union[str, None] = 'd20bec2f3d2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meal_entries', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(length=64),
               comment='Client-generated unique ID',
               existing_comment='UUID4 primary key',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meal_entries', 'id',
               existing_type=sa.String(length=64),
               type_=sa.UUID(),
               comment='UUID4 primary key',
               existing_comment='Client-generated unique ID',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    # ### end Alembic commands ###
