"""Add meal_entries table

Revision ID: d20bec2f3d2e
Revises: c39e3bc1eb5a
Create Date: 2026-08-12 22:38:56.581760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd20bec2f3d2e'
down_revision: Union[str, None] = 'c39e3bc1eb5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_entries',
    sa.Column('firebase_uid', sa.String(length=128), nullable=False, comment='Firebase UID of the user who logged this meal'),
    sa.Column('date', sa.String(length=10), nullable=False, comment='Date of the meal (YYYY-MM-DD)'),
    sa.Column('food_name', sa.String(length=255), nullable=False, comment='Name of the food'),
    sa.Column('calories', sa.Float(), nullable=False, comment='Total calories'),
    sa.Column('protein', sa.Float(), nullable=False, comment='Total protein in grams'),
    sa.Column('carbs', sa.Float(), nullable=False, comment='Total carbohydrates in grams'),
    sa.Column('fats', sa.Float(), nullable=False, comment='Total fats in grams'),
    sa.Column('meal_type', sa.String(length=50), nullable=False, comment='Type of meal: breakfast, lunch, dinner, snack'),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False, comment='When the meal was logged'),
    sa.Column('source', sa.String(length=50), server_default='manual', nullable=False, comment='Source of entry: manual | ai_scan'),
    sa.Column('serving_size', sa.Float(), nullable=True, comment='Serving size in grams'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='UUID4 primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp (server-side)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp (auto-refreshed on UPDATE)'),
    sa.PrimaryKeyConstraint('id'),
    comment='User logged meal history'
    )
    op.create_index('ix_meal_entries_date', 'meal_entries', ['date'], unique=False)
    op.create_index('ix_meal_entries_firebase_uid', 'meal_entries', ['firebase_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_meal_entries_firebase_uid', table_name='meal_entries')
    op.drop_index('ix_meal_entries_date', table_name='meal_entries')
    op.drop_table('meal_entries')
    # ### end Alembic commands ###
